dist: trusty
language: python
matrix:
  include:
    - python: "2.6"
      env: TOXENV=py26
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.6"
      env: TOXENV=py36
    - python: "2.7"
      env: TOXENV=flake8
install:
    - pip install -r tests/requirements.txt
    - pip install tox
# command to run tests
script:
  tox
